language: ruby
cache: bundler

rvm:
  - 2.5
  - 2.6
  - 2.7

gemfile:
  - gemfiles/activesupport_5.x.gemfile
  - gemfiles/activesupport_6.x.gemfile

before_install: gem update bundler
bundler_args: --without production

notifications:
  webhooks: https://idobata.io/hook/047eeb76-6f1f-4fc2-82f8-f8abceacd51e
